name: Shane Peters
favicon: null
layout_spectrum: 0.52755
typography_spectrum: 0.53465
title: 'Shane Peters, DP'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#667787'
    - '#485973'
    - '#161616'
    - '#d3c5a8'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
