name: Shane Peters
favicon: null
layout_spectrum: 0.87584
typography_spectrum: 0.53465
title: 'Shane Peters, DP'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#667787'
    - '#485973'
    - '#161616'
    - '#d3c5a8'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
