name: Shane Peters
favicon: null
layout_spectrum: 0.87584
typography_spectrum: 0.695273396326229
title: 'Shane Peters, DP'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
